
version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0
    working_directory: /go/src/github.com/circleci/gomail
    steps:
      - checkout
      - run:
          command: |
            set -eu
            go get -t -d -v ./...
            go test -v -race ./...